profiles:
  - develop-net
devices:
  root:
    path: /
    pool: pool
    size: 32GB
    type: disk
config:
  limits.cpu: '8'
  limits.memory: 16GiB
  cloud-init.user-data: |
    #cloud-config
    package_upgrade: true
    apt:
      sources:
        go.list:
          source: "deb https://ppa.launchpadcontent.net/longsleep/golang-backports/ubuntu $RELEASE main"
          keyid: f6bc817356a3d45e
    packages:
      # distrobuilder
      - golang-go
      - debootstrap
      - rsync
      - gpg
      - squashfs-tools
      - git
      - make
      # repack-windows
      - genisoimage
      - libwin-hivex-perl
      - wimtools
    write_files:
    - content: |
        #!/bin/bash
        cd /distrobuilder
        make
        /root/go/bin/distrobuilder repack-windows /Win* /LXD-Windows.iso
      path: /usr/local/bin/create
      permissions: '0777'
    runcmd:
      - git clone https://github.com/lxc/distrobuilder
      - mount -t 9p config /mnt && cd /mnt && ./install.sh
      - systemctl start lxd-agent
